# Generated by Django 5.2.3 on 2025-06-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PekerjaanMitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan_kegiatan', models.CharField(max_length=20)),
                ('nama_mitra', models.CharField(max_length=100)),
                ('tim_kerja', models.CharField(max_length=100)),
                ('kegiatan', models.CharField(max_length=200)),
                ('volume', models.FloatField()),
                ('satuan', models.CharField(max_length=50)),
                ('honor_per_satuan', models.IntegerField()),
                ('nilai_pekerjaan', models.IntegerField()),
                ('mulai_kegiatan', models.DateField()),
                ('selesai_kegiatan', models.DateField()),
                ('beban_anggaran', models.CharField(max_length=100)),
            ],
        ),
    ]
