# Generated by Django 5.2.3 on 2025-06-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekerjaan', '0002_mitra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tim', models.CharField(max_length=100)),
                ('nama_kegiatan', models.CharField(max_length=255)),
            ],
        ),
    ]
