# Generated by Django 5.2.3 on 2025-06-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekerjaan', '0003_timkegiatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BebanHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tim', models.CharField(max_length=100)),
                ('beban', models.CharField(max_length=100)),
                ('rincian', models.TextField()),
                ('honor', models.IntegerField()),
                ('satuan', models.CharField(max_length=50)),
            ],
        ),
    ]
